### ISSUE TITLE
the test file seem to fail in v1.2

### ISSUE THREAD

**Issue by jeanph01** [tautologistics/node-htmlparser#1]
Can you verify that the test file works in v.1.2 ?

**Comment by tautologistics** [comment]
runtests.js or runtests.html? Both work with node 0.1.92 and 0.1.93.

What version of node are you using and what errors are you encountering?

**Comment by jeanph01** [comment]
It was the html file. 
My code is in this folder: D:\zip\code\javascript\htmlparser-v1.2.0

and opening it in firefox 3.6 i get a bunch of :
Exception occured during test: TypeError: parser.ParseComplete is not a function

in ie6 this gives:
Exception occured during test: [object Error]

If I test it with v1.1.0 it pass in firefox but fail with the same message in ie6.

**Comment by tautologistics** [comment]
Can you give v1.3.1 a whirl? It definitely work with Firefox 3.6.3, Chrome 5, Safari 4.0.5, and IE 8.

I've found some problems with Opera and IE6/7 that I am looking into.

**Comment by tautologistics** [comment]
Opera is working now. Feel free to submit patches for IE6/7 =)

**Comment by tautologistics** [comment]
Found the problem with IE 6/7. Forgot it doesn't support strings as char arrays so I switched to using charAt(). v1.3.4 is working in all browsers I have available.

**Comment by jeanph01** [comment]
Yes this is fixed now. Good ! :-)
